
version: '3'
services:
  db:
    restart: always
    image: postgres
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=docker
     - POSTGRES_USER=postgres
     - POSTGRES_DB=contact_manager
    volumes:
     - pgvolDev:/var/lib/postgresql/data
  pgAdmin:
    restart: always
    image: dpage/pgadmin4
    ports:
     - "8006:80"
    environment:
     - PGADMIN_DEFAULT_EMAIL=dev@docker.org
     - PGADMIN_DEFAULT_PASSWORD=docker
    volumes:
     - pgadminDev:/var/lib/pgadmin
  app:
    restart: always
    build: .
    image: contact-manger
    ports:
    - "8030:3000"
    depends_on:
    - db

volumes:
    pgvolDev:
    pgadminDev:
